# Generated by Django 4.2.30 on 2026-09-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_types', '0002_feetype_currency_feetype_recurring_frequency_and_more'),
        ('student_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='fee_type_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invoices', to='fee_types.feetypeclass'),
        ),
        migrations.AlterField(
            model_name='studentinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('payment_submitted', 'Payment Submitted'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.UniqueConstraint(fields=('class_student', 'fee_type', 'invoice_date'), name='unique_invoice_per_student_fee_type_date'),
        ),
    ]
