# Generated by Django 4.2.30 on 2026-08-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guardian',
            table='guardians',
        ),
    ]
