# Generated by Django 4.2.30 on 2026-08-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentguardian_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='studentguardian',
            table='student_guardians',
        ),
    ]
