# Generated by Django 4.2.30 on 2026-09-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_table_alter_studentguardian_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('OUT', 'Out'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20),
        ),
    ]
