# Generated by Django 4.2.30 on 2026-09-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_image_data'),
        ('students', '0004_student_status'),
    ]

    operations = [
    ]
