# Generated by Django 4.2.30 on 2026-09-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_merge_20260908_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('out', 'Out'), ('graduated', 'Graduated')], default='ACTIVE', max_length=20),
        ),
    ]
