# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classstudent_classstudent_unique_class_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='classes.class')),
                ('class_teacher', models.ForeignKey(db_column='class_teacher_id', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='classes.classteacher')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-start_date'],
            },
        ),
    ]
