# Generated by Django 4.2.30 on 2026-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_merge_student_assessments_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentimage',
            name='image_data',
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='image_data',
            field=models.JSONField(blank=True, default=None, help_text='Stores media metadata: {id, storage, object_key, filename, content_type, size, width, height}', null=True),
        ),
    ]
