# Generated by Django 4.2.30 on 2026-09-08 08:07

from django.db import migrations, models


def create_assessment_join_tables(apps, schema_editor):
    """Create tables from the removed assessment apps on fresh databases.

    Migration 0002 intentionally only added these models to Django's migration
    state because the tables already existed in the original deployment.  A
    fresh database does not have those tables, so create any that are missing
    before altering ``AssessmentImage.image_data`` below.
    """
    existing_tables = set(schema_editor.connection.introspection.table_names())

    for model_name in ("StudentAssessment", "AssessmentImage"):
        model = apps.get_model("assessments", model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_merge_student_assessments_images'),
    ]

    operations = [
        migrations.RunPython(
            create_assessment_join_tables,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='assessmentimage',
            name='image_data',
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='image_data',
            field=models.JSONField(blank=True, default=None, help_text='Stores media metadata: {id, storage, object_key, filename, content_type, size, width, height}', null=True),
        ),
    ]
