# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_table_alter_studentguardian_table'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='activities/images/')),
                ('caption', models.TextField(blank=True)),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_images', to='students.student')),
            ],
            options={
                'db_table': 'activity_images',
            },
        ),
    ]
