# Generated by Django 4.2.30 on 2026-08-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_branch_table_alter_school_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='schools.branch')),
            ],
            options={
                'db_table': 'fee_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_fee_type_per_branch'),
        ),
    ]
