# Generated by Django 4.2.30 on 2026-09-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classstudent_student_related_name'),
        ('fee_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='currency',
            field=models.CharField(default='IDR', max_length=10),
        ),
        migrations.AddField(
            model_name='feetype',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FeeTypeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='fee_type_classes', to='classes.class')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_type_classes', to='fee_types.feetype')),
            ],
            options={
                'db_table': 'fee_type_classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feetypeclass',
            constraint=models.UniqueConstraint(fields=('fee_type', 'class_obj'), name='unique_fee_type_class'),
        ),
    ]
