# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('report_sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='report_section',
            field=models.ForeignKey(db_column='report_section_id', on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='report_sections.reportsection'),
        ),
    ]
