# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0002_initial'),
        ('score_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='score_setting',
            field=models.ForeignKey(db_column='score_setting_id', on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='score_settings.scoresetting'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('report_section', 'title'), name='unique_indicator_per_report_section'),
        ),
    ]
