# Generated by Django 4.2.30 on 2026-09-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_staff_user'),
        ('student_invoices', '0002_studentinvoice_fee_type_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=30)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='student_invoices.studentinvoice')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='staffs.staff')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.JSONField(help_text='Uploaded image metadata (e.g. R2 file key, URL, original name)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_proofs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
