# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_branch_table_alter_school_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('score_type', models.CharField(choices=[('numeric', 'Numeric'), ('level', 'Level')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_settings', to='schools.branch')),
            ],
            options={
                'db_table': 'score_settings',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='scoresetting',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_score_setting_per_branch'),
        ),
    ]
