# Generated by Django 4.2.30 on 2026-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_settings', '0002_merge_numeric_level_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresetting',
            name='score_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('LEVEL', 'Level')], max_length=20),
        ),
    ]
