# Generated by Django 4.2.30 on 2026-08-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_revokedaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='STAFF', max_length=20),
        ),
    ]
