# Generated by Django 4.2.30 on 2026-10-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rolemodulepermission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolemodulepermission',
            table='user_role_permissions',
        ),
    ]
