# Generated by Django 4.2.30 on 2026-10-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rolemodulepermission_table'),
        ('users', '0005_parent_users_api_access'),
    ]

    operations = [
    ]
