# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0003_alter_student_table_alter_studentguardian_table'),
        ('level_scores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='assessments.assessment')),
                ('level_score', models.ForeignKey(blank=True, db_column='level_score_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assessments', to='level_scores.levelscore')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='students.student')),
            ],
            options={
                'db_table': 'student_assessments',
            },
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='unique_student_assessment'),
        ),
    ]
