# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_layouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_layout', models.ForeignKey(db_column='report_layout_id', on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='report_layouts.reportlayout')),
            ],
            options={
                'db_table': 'report_sections',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('report_layout', 'name'), name='unique_report_section_per_layout'),
        ),
    ]
