# Generated by Django 4.2.30 on 2026-08-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
        ('schools', '0002_alter_branch_table_alter_school_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academic_years.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.branch')),
            ],
            options={
                'db_table': 'school_brach_classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('branch', 'academic_year', 'name'), name='unique_class_per_branch_academic_year'),
        ),
    ]
