# Generated by Django 4.2.30 on 2026-08-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='classes.class')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teaching_assignments', to='staffs.staff')),
            ],
            options={
                'db_table': 'class_teachers',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='classes', through='classes.ClassTeacher', to='staffs.staff'),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(fields=('class_obj', 'staff'), name='unique_class_teacher'),
        ),
    ]
