# Generated by Django 4.2.30 on 2026-08-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentguardian_and_more'),
        ('classes', '0002_classteacher_class_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student_assignments', to='students.student')),
            ],
            options={
                'db_table': 'class_students',
            },
        ),
        migrations.AddConstraint(
            model_name='classstudent',
            constraint=models.UniqueConstraint(fields=('class_obj', 'student'), name='unique_class_student'),
        ),
    ]
