# Generated by Django 4.2.30 on 2026-09-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classstudent_classstudent_unique_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Only one class should be marked as current per student'),
        ),
    ]
