# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'level_scores',
                'ordering': ['score_setting', 'position'],
            },
        ),
    ]
