# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level_scores', '0001_initial'),
        ('score_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelscore',
            name='score_setting',
            field=models.ForeignKey(db_column='score_setting_id', on_delete=django.db.models.deletion.CASCADE, related_name='level_scores', to='score_settings.scoresetting'),
        ),
        migrations.AddConstraint(
            model_name='levelscore',
            constraint=models.UniqueConstraint(fields=('score_setting', 'position'), name='unique_level_score_position'),
        ),
        migrations.AddConstraint(
            model_name='levelscore',
            constraint=models.UniqueConstraint(fields=('score_setting', 'name'), name='unique_level_score_name'),
        ),
    ]
