# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumericScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'numeric_scores',
            },
        ),
    ]
