# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numeric_scores', '0001_initial'),
        ('score_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericscore',
            name='score_setting',
            field=models.OneToOneField(db_column='score_setting_id', on_delete=django.db.models.deletion.CASCADE, related_name='numeric_score', to='score_settings.scoresetting'),
        ),
    ]
