# Generated by Django 4.2.30 on 2026-08-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='school_branches',
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
    ]
