# Generated by Django 4.2.30 on 2026-09-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_code'),
        ('schools', '0003_alter_school_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='locations.location'),
            preserve_default=False,
        ),
    ]
