# Generated by Django 4.2.30 on 2026-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='school',
        ),
    ]
