# Generated by Django 4.2.30 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0002_remove_academicyear_school'),
        ('schools', '0002_alter_branch_table_alter_school_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.branch'),
            preserve_default=False,
        ),
    ]