# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classstudent_classstudent_unique_class_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateField()),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='classes.class')),
                ('class_teacher', models.ForeignKey(db_column='class_teacher_id', on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='classes.classteacher')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
