# Generated by Django 4.2.30 on 2026-09-01 08:22

from django.db import migrations, models
import django.utils.timezone


def create_activity_join_tables(apps, schema_editor):
    """Create tables moved from the removed activity apps on fresh databases."""
    existing_tables = set(schema_editor.connection.introspection.table_names())

    for model_name in ("ActivityImage", "ActivityStudent"):
        model = apps.get_model("activities", model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_table_alter_studentguardian_table'),
        ('activities', '0002_merge_activity_images_students'),
    ]

    operations = [
        migrations.RunPython(
            create_activity_join_tables,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='activityimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='students',
            field=models.ManyToManyField(related_name='activities', through='activities.ActivityStudent', to='students.student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activitystudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
