# Generated by Django 4.2.30 on 2026-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_options_alter_activityimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudent',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitystudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
