# Generated by Django 4.2.30 on 2026-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitystudent_position_activitystudent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
