# Generated by Django 4.2.30 on 2026-09-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activityimage_image_data'),
        ('activities', '0005_activity_is_publish'),
    ]

    operations = [
    ]
