# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='assessments/images/')),
                ('caption', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'assessment_images',
            },
        ),
    ]
