# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_images', '0001_initial'),
        ('student_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentimage',
            name='student_assessment',
            field=models.ForeignKey(db_column='student_assessment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_images', to='student_assessments.studentassessment'),
        ),
    ]
