# Generated by Django 4.2.30 on 2026-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_branch_table_alter_school_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_layouts', to='schools.branch')),
            ],
            options={
                'db_table': 'report_layouts',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportlayout',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_report_layout_per_branch'),
        ),
    ]
